#!/bin/bash

set -e

# Helper script for running command while the server is running.

HERE="$(dirname "$0")"
TOP="$HERE/.."

# Run up the simulation server.  We won't use valgrind for these validation
# tests, really just to speed things up.  For a consistent state, we reset the
# persistence file.
"$TOP"/simserver -n -P -E-qn &
SIM_PID=$!
trap 'kill -s SIGINT $SIM_PID; wait $SIM_PID' EXIT

# Wait for the server to start
sleep 0.2
while !( echo '*IDN?' ) | nc localhost 8888; do
    echo connecting...
    sleep 0.2
done
echo 'Connected to server'

# Run the command we've been given
"$@"
