#!/bin/sh

# Startup script for Panda server on target machine.

. /etc/init.d/functions

# File locations
server_pid_file=/var/run/panda-server.pid
extension_pid_file=/var/run/panda-extensions.pid

panda_server=/opt/bin/panda_server
panda_config=/opt/share/panda-fpga/config_d
panda_module=/opt/share/panda-server/panda.ko
panda_state=/opt/state/panda.state
panda_mac=/qspi/MAC.FPGA

extension_server=/opt/share/panda-server/extension_server
extension_dir=/opt/share/panda-fpga/extensions

load_panda_firmware=/opt/share/panda-fpga/load-panda-firmware


fail()
{
    echo >&2 "$@"
    exit 1
}


do_start()
{
    # Only set the MAC addresses if the file is present
    panda_server_mac=""
    if [ -e $panda_mac ]; then
        panda_server_mac="-M $panda_mac"
    fi

    [ -x $load_panda_firmware ]  ||  fail 'PandA firmware not installed'


    # Remove the kernel module before reloading the FPGA if loaded.  If this
    # rmmod fails then we can't proceed.
    if lsmod | grep -q '^panda\>'; then
        rmmod panda
    fi  &&

    # Load the Panda FPGA firmware.  This can fail, in which case the poor user
    # will have to inspect the logs!
    $load_panda_firmware  &&

    # Now we can load the module and go
    insmod $panda_module  &&

    # After inserting Panda module wait for devices to appear
    i=0  &&
    while [ $i -lt 10 ]; do
        sleep 0.5
        [ -e /dev/panda.map ]  &&  break
        i=$((i+1))
    done  &&

    # Now start the extension server (in procServ if available)
    {
        if type procServ &> /dev/null; then
            procServ -n panda-extensions -p $extension_pid_file \
                -L /var/log/panda-extensions-console 8021 \
                $extension_server -s $extension_dir
        else
            $extension_server -d -s $extension_dir -P $extension_pid_file
        fi
    } &&
    {
        # Finally start the PANDA server (in procServ if available)
        if type procServ &> /dev/null; then
            procServ -n panda-server -p $server_pid_file \
                -L /var/log/panda-server-console 8022 \
                $panda_server \
                    -c $panda_config -f $panda_state -R -X 9999 \
                    -r "$(head -n1 /etc/version)" \
                    $panda_server_mac
        else
            $panda_server \
                -c $panda_config -f $panda_state -P $server_pid_file -D -R \
                -X 9999 -r "$(head -n1 /etc/version)" \
                $panda_server_mac
        fi
    }
}

do_stop()
{
    kill $(cat $server_pid_file)  &&
    kill $(cat $extension_pid_file) &&

    # Remove the Panda driver.  We have to keep trying because we can't actually
    # unload it until the server has finished shutting down.
    i=0  &&
    while [ $i -lt 10 ]; do
        sleep 0.5
        rmmod panda  &&  break
        i=$((i+1))
    done
}

do_start_stop "$1" panda-server
