#!/bin/sh

# Startup script for Panda server on target machine.

. /etc/init.d/functions

# File locations
pidfile=/var/run/panda-server.pid

carrier_firmware=/opt/share/panda/panda_top.bit
slow_firmware=/opt/share/panda/slow_top.bin

panda_server=/opt/bin/panda_server
panda_config=/opt/share/panda/config_d
panda_module=/opt/share/panda/panda.ko
panda_state=/opt/state/panda.state
slow_load=/opt/bin/slow_load


fail()
{
    echo >&2 "$@"
    return 1
}


do_start()
{
    { [ -e $carrier_firmware -a -e $slow_firmware ]  ||
        fail "Firmware not installed"; }  &&
    cat $carrier_firmware >/dev/xdevcfg  &&
    $slow_load <$slow_firmware  &&
    insmod $panda_module  &&

    # After inserting Panda module wait for devices to appear
    i=0  &&
    while [ $i -lt 10 ]; do
        sleep 0.5
        [ -e /dev/panda.map ]  &&  break
        i=$((i+1))
    done

    $panda_server -c $panda_config -f $panda_state -P $pidfile -D -R
}

do_stop()
{
    kill -HUP $(cat $pidfile)  &&

    # Remove the Panda driver.  We have to keep trying because we can't actually
    # unload it until the server has finished shutting down.
    i=0  &&
    while [ $i -lt 10 ]; do
        sleep 0.5
        rmmod panda  &&  break
        i=$((i+1))
    done
}

do_start_stop "$1" panda-server
