EXTRA_CFLAGS += -std=gnu99
EXTRA_CFLAGS += -Werror
EXTRA_CFLAGS += -Wextra
EXTRA_CFLAGS += -Wno-declaration-after-statement
EXTRA_CFLAGS += -Wno-unused-parameter
EXTRA_CFLAGS += -Wno-missing-field-initializers

# Suppress some kernel error messages
EXTRA_CFLAGS += -Wno-empty-body

obj-m := panda.o

panda-objs += panda_core.o
panda-objs += panda_map.o
panda-objs += panda_stream.o

# vim: set filetype=make:
