# Python script for generatign panda_drv.h from *DRV entries in registers
# configuration file.

from __future__ import print_function

import sys

from parse_indent import parse_register_file
registers = parse_register_file(sys.argv[1])

base, fields = registers['*DRV']
base = int(base)

print('''\
/* Register definitions derived from configuration registers *DRV section.
 *
 * This file is automatically generated from driver/panda_drv.py.
 * Do not edit this file. */
''')
for name, field in fields:
    reg = int(field)
    print('#define %s 0x%05x' % (name, (base << 12) | (reg << 2)))
