# Python script for generatign panda_drv.h from *DRV entries in registers
# configuration file.

from __future__ import print_function

import sys

from parse_indent import parse_register_file
blocks, constants = parse_register_file(sys.argv[1])
compat_version = 'DRIVER_COMPAT_VERSION'

print(''' \
/* Register definitions derived from configuration registers *DRV and *REG
 * sections.
 *
 * This file is automatically generated from driver/panda_drv.py.
 * Do not edit this file. */
''')

for block_name in ('*DRV', '*REG'):
    base, fields = blocks[block_name]
    base = int(base)

    for name, field in fields:
        # Take the first number of the field
        reg = int([item for item in field.split() if item.isdigit()][0])
        print('#define %s_%s 0x%05x' % (block_name[1:],
                                        name, (base << 12) | (reg << 2)))

    print('')

print('#define %s %s' % (compat_version, constants[compat_version]))
