# Python script for generatign panda_drv.h from *DRV entries in registers
# configuration file.

from __future__ import print_function

import sys

from parse_indent import parse_register_file
blocks, constants = parse_register_file(sys.argv[1])

base, fields = blocks['*DRV']
base = int(base)

compat_version = 'DRIVER_COMPAT_VERSION'

print('''\
/* Register definitions derived from configuration registers *DRV section.
 *
 * This file is automatically generated from driver/panda_drv.py.
 * Do not edit this file. */
''')
for name, field in fields:
    reg = int(field)
    print('#define %s 0x%05x' % (name, (base << 12) | (reg << 2)))

print('')
print('#define %s %s' % (compat_version, constants[compat_version]))
