name: Code CI 

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: ["zynq", "zynqmp"]

    runs-on: ubuntu-latest
    steps:

      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-server

      - name: Checkout PandABlocks-rootfs
        uses: actions/checkout@v2
        with:
          repository: PandABlocks/PandABlocks-rootfs
          path: PandABlocks-rootfs
          ref: containers-tizayi

      # Build
      - name: Make PandABlocks-rootfs kernel
        run: |
          cd PandABlocks-rootfs
          make kernel

      - name: Make zpkg
        run: |
          cd PandABlocks-server
          make zpkg

      # Artifacts
      - name: Upload zpkg
        uses: actions/upload-artifact@v2
        with:
          name: zpkgs
          path: build-server/panda-server@*.zpg

  release:
    needs: [build]
    runs-on: ubuntu-latest
    # make a release on every tag
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: zpkgs
          path: zpkgs

      - name: Github Release
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: softprops/action-gh-release@2d72d869af3bf23602f9593a1e3fd739b80ac1eb  # v0.1.12
        with:
          files: zpkgs/*
          body: See [Changelog](CHANGELOG.rst) for more details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

