name: Docs CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-server
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      # System dependencies
      - name: Install system dependencies
        run: sudo pip install sphinx sphinx-rtd-theme docutils==0.16

      # CONFIG files
      - name: Generate CONFIG files - zynq
        run: sudo bash PandABlocks-server/.github/scripts/config-file-server.sh zynq

      # Build
      - name: Build Docs
        run: |
          cd PandABlocks-server
          make docs

      # Verification of build files
      #- name: List build files
      #  run: ls ${{ github.workspace }}/build/html
      
      # Publish
      - uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: ${{ github.ref }}
          split-by: /
      
      - name: Move to versioned directory
        # e.g. master or 0.1.2
        run: |
          mkdir PandABlocks-server/.github/pages
          mv build-server/html "PandABlocks-server/.github/pages/${{ steps.split.outputs._2 }}"

      - name: Publish Docs to gh-pages
        # Only master and tags are published
        if: "${{ github.repository_owner == 'dls-controls' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}"
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: PandABlocks-server/.github/pages
          keep_files: true