name: Make Server CI 

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: ["zynq", "zynqmp"]

    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-server

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs

      - name: Checkout PandABlocks-rootfs
        uses: actions/checkout@v2
        with:
          repository: PandABlocks/PandABlocks-rootfs
          ref: ci-build
          path: PandABlocks-rootfs

      # ARM GNU Toolchain
      - name: Download Arm GNU toolchain - ${{ matrix.platform }}
        run: sudo bash PandABlocks-rootfs/.github/scripts/GNU-toolchain.sh ${{ matrix.platform }}

      # Tar dependancies (Linux only)
      - name: Download tar file dependencies
        run: sudo bash PandABlocks-rootfs/.github/scripts/tar-files.sh -l

      # System dependencies (required for build)
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libncurses5-dev expat
          sudo pip install rst2pdf sphinx sphinx-rtd-theme docutils==0.16

      # CONFIG files
      - name: Generate rootfs CONFIG files - ${{ matrix.platform }}
        run: |
          mkdir build
          sudo bash PandABlocks-rootfs/.github/scripts/config-file-rootfs.sh ${{ matrix.platform }}
      
      - name: Generate server CONFIG files - ${{ matrix.platform }}
        run: |
          mkdir build-server
          sudo bash PandABlocks-server/.github/scripts/config-file-server.sh ${{ matrix.platform }}

      # Verification of files/file structure
      #- name: List workspace files
      #  run: |
      #    ls ${{ github.workspace }}
      #    echo " "
      #    ls PandABlocks-server
      #    echo " "
      #    ls PandABlocks-rootfs
      #    echo " "
      #    ls rootfs
      #    echo " "
      #    ls tar-files
      #    echo " "

      # Build pandABlocks-rootfs
      - name: Make zips
        run: |
          cd PandABlocks-rootfs
          make kernel

      # Build zpkg
      - name: Make zpkg
        run: |
          cd PandABlocks-server
          make zpkg

      # Verification of build files
      #- name: List build files
      #  run: |
      #    ls build
      #    echo " "
      #    ls build-server/server
      #    echo " "

      # Artifacts
      - name: Upload zpkg
        uses: actions/upload-artifact@v2
        with:
          name: build-files-${{ matrix.platform }}
          path: |
            build-server/panda-server*.zpg

      # Release 
      - name: Release
        uses: softprops/action-gh-release@v1
        # Only release when a tag is pushed
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build-server/panda-server*.zpg
          body_path: ${{ github.workflow }}/pandABlocks-server/CHANGELOG.rst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

