name: Tests CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-server

      # System dependencies (required for build)
      - name: Install system dependencies
        run: |
          sudo pip install sphinx sphinx-rtd-theme docutils==0.16

      # CONFIG files
      - name: Generate CONFIG files - zynq
        run: |
          mkdir build-server
          sudo bash PandABlocks-server/.github/scripts/config-files.sh zynq
        shell: bash

      # Build pandABlocks-rootfs
      - name: Make tests
        run: |
          cd PandABlocks-server
          make tests
